apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: grafana-ingress
 namespace: monitoring
 annotations:
   kubernetes.io/tls-acme: "true"
   kubernetes.io/ingress.class: "nginx"
spec:
 rules:
 - host: grafana.rajputshashank.tk
   http:
     paths:
     - path: /
       backend:
         serviceName: grafana
         servicePort: 80
